version: "3.9"

services:
  frontend:
    build: ./client
    container_name: billstack-frontend
    ports:
      - "3001:4173"
    depends_on:
      - backend
    networks:
      - billstack-net

  backend:
    build: ./server
    container_name: billstack-backend
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    networks:
      - billstack-net

  mongo:
    image: mongo:6
    container_name: billstack-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - billstack-net

  prometheus:
    image: prom/prometheus
    container_name: prom-server
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
    networks:
      - billstack-net
    depends_on:
      - backend

volumes:
  mongo-data:

networks:
  billstack-net:
