scrape_configs:
  - job_name: 'billstack-backend'
    scrape_interval: 15s
    static_configs:
      - targets: ['backend:8000']
    metrics_path: /metrics
    scheme: http
    basic_auth:
      username: admin   
      password: 2320403108 
