version: "3"

services:
  prom-server:
    image: prom/prometheus
    ports:
      - "9090:9090"  # This is a proper list item
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
